### ISSUE TITLE
pb with shared library prevents starting yadoms executable

### ISSUE THREAD

**Issue by gascof** [Yadoms/yadoms#230]
Yadoms (v2.0.0-rc.2 for RPi) was installed by copying the full folder to /home/pi/domotique/yadoms
Traget OS: Raspbian jessie

Requesting to run yadoms executable (/home/pi/domotique/yadoms/yadoms) returns:
/home/pi/domotique/yadoms/yadoms: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory

**Comment by jano42** [comment]
Just install libpq

sudo apt-get install libpq-dev

It should fix it

**Comment by jano42** [comment]
Sorry the package is libpq5

sudo apt-get install libpq5

**Comment by gascof** [comment]
I tried before getting the 2nd message, so I installed libpq-dev.
Solved the start-up problem.

I'll install libpq5, in case it may prevent other functionnalities later on

Thank you for such a prompt answer

**Comment by sgallou** [comment]
Re-open this issue as problem still exist. We must at least document it on the web site, or update the Raspberry package to contain this lib.

**Comment by sgallou** [comment]
From now, Yadoms doesn't depend of libpq if SQLite selected in yadoms.ini file.
A comment was added in yadoms.ini file to install dependency when selecting PostGreSql database.
libpq5 package is present in Raspberry-Pi SD card image.
